name: CI for gaussdb-python

on:
  push:
    branches:
        - "*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
    
jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      opengauss:
        image: opengauss/opengauss-server:latest
        ports:
          - 5432:5432
        env:
          GS_USERNAME: ${{ secrets.OPENGAUSS_USERNAME }}
          GS_USER_PASSWORD: ${{ secrets.OPENGAUSS_PASSWORD }}
          GS_PASSWORD: ${{ secrets.OPENGAUSS_PASSWORD }}
        options: >-
          --privileged=true
          --name opengauss-custom

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          echo "VENV_PATH=$GITHUB_WORKSPACE/venv/bin" >> $GITHUB_ENV
          source venv/bin/activate

      - name: Install gaussdb libpq driver
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget -O /tmp/GaussDB_driver.zip https://dbs-download.obs.cn-north-1.myhuaweicloud.com/GaussDB/1730887196055/GaussDB_driver.zip
          unzip /tmp/GaussDB_driver.zip -d /tmp/ && rm -rf /tmp/GaussDB_driver.zip
          \cp /tmp/GaussDB_driver/Centralized/Hce2_X86_64/GaussDB-Kernel*64bit_Python.tar.gz /tmp/
          tar -zxvf /tmp/GaussDB-Kernel*64bit_Python.tar.gz -C /tmp/ && rm -rf /tmp/GaussDB-Kernel*64bit_Python.tar.gz && rm -rf /tmp/psycopg2 && rm -rf /tmp/GaussDB_driver
          echo /tmp/lib | sudo tee /etc/ld.so.conf.d/gauss-libpq.conf
          sudo sed -i '1s|^|/tmp/lib\n|' /etc/ld.so.conf
          sudo ldconfig
          ldconfig -p | grep pq
           
      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e "./psycopg[dev,test]"
          pip install -e ./psycopg_pool

          
      - name: Wait for openGauss to be ready
        env:
          GSQL_PASSWORD: ${{ secrets.OPENGAUSS_PASSWORD }}
        run: |
          source venv/bin/activate
          for i in {1..15}; do
            pg_isready -h localhost -p 5432 -U ${{ secrets.OPENGAUSS_USERNAME }} && break
            sleep 5
          done
          if ! pg_isready -h localhost -p 5432 -U ${{ secrets.OPENGAUSS_USERNAME }}; then
            echo "openGauss is not ready"
            exit 1
          fi

      - name: Create test database
        run: |
          docker exec opengauss-custom bash -c "su - omm -c 'gsql -d postgres -c \"CREATE DATABASE test DBCOMPATIBILITY '\''PG'\'';\"'"

      - name: Create report directory
        run: |
          mkdir -p reports

      - name: Run tests
        env:
          PYTHONPATH: ./psycopg:./psycopg_pool
          PSYCOPG_IMPL: python
          PSYCOPG_TEST_DSN: "host=127.0.0.1 port=5432 dbname=test user=${{ secrets.OPENGAUSS_USERNAME }} password=${{ secrets.OPENGAUSS_PASSWORD }} "
        run: |
          source venv/bin/activate
          pytest -s -v

      - name: Cleanup
        if: always()
        run: |
          docker stop opengauss-custom
          docker rm opengauss-custom
